DROP PROCEDURE P_PROJECT_STATE_SCAN;//

CREATE PROCEDURE P_PROJECT_STATE_SCAN()
BEGIN

        -- 把融资时间已到的项目的状态改掉，并记录项目生命周期。
        -- 因为这个是前台无法被主动触发的。而对于融资还未到期金额已满的项目，则PHP即可处理
        CREATE TEMPORARY TABLE IF NOT EXISTS TMP_PROJECTS  
        (  
                PROJECT_ID INTEGER,
                RSLT VARCHAR(20)
        );  
        TRUNCATE TABLE TMP_PROJECTS;  -- 使用前先清空临时表。
        
        INSERT INTO TMP_PROJECTS 
        SELECT ID, 'RAISE_SUCCESS' FROM  PROJECTS WHERE STATE = 'RAISE' AND RAISE_END_DATE < CURRENT_DATE() AND RAISED_BAL >= MIN_RAISE_QUOTA;
        
        INSERT INTO TMP_PROJECTS 
        SELECT ID, 'RAISE_FAILED' FROM  PROJECTS WHERE STATE = 'RAISE' AND RAISE_END_DATE < CURRENT_DATE() AND RAISED_BAL < MIN_RAISE_QUOTA;
        
        UPDATE PROJECTS SET STATE = 'RAISE_SUCCESS',UPDATED_AT = CURRENT_TIMESTAMP WHERE ID IN (SELECT PROJECT_ID FROM TMP_PROJECTS WHERE RSLT = 'RAISE_SUCCESS');
        INSERT INTO PROJECT_LIFE_EVENTS (PROJECT_ID, EVENT_TYPE, EVENT_DESC, EVENT_DATE, CREATED_AT, UPDATED_AT) 
        SELECT PROJECT_ID, 'RAISE_SUCCESS', '融资成功', CURRENT_DATE(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM TMP_PROJECTS WHERE RSLT = 'RAISE_SUCCESS';
        
        UPDATE PROJECTS SET STATE = 'RAISE_FAILED',UPDATED_AT = CURRENT_TIMESTAMP WHERE ID IN (SELECT PROJECT_ID FROM TMP_PROJECTS WHERE RSLT = 'RAISE_FAILED');
        INSERT INTO PROJECT_LIFE_EVENTS (PROJECT_ID, EVENT_TYPE, EVENT_DESC, EVENT_DATE, CREATED_AT, UPDATED_AT) 
        SELECT PROJECT_ID, 'RAISE_SUCCESS', '融资失败', CURRENT_DATE(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM TMP_PROJECTS WHERE RSLT = 'RAISE_FAILED';
        
        -- 我运行过了
        INSERT INTO PROCEDURE_LOGS (PROC_NAME, MESSAGE, CREATED_AT, UPDATED_AT) VALUES ('P_PROJECT_STATE_SCAN', 'OK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
        
        DROP TEMPORARY TABLE IF EXISTS TMP_PROJECTS;

END//



DROP EVENT IF EXISTS E_PROJECT_STATE_SCAN;//
CREATE EVENT IF NOT EXISTS E_PROJECT_STATE_SCAN ON SCHEDULE EVERY 60 SECOND ON COMPLETION PRESERVE DO CALL P_PROJECT_STATE_SCAN();//
